export const actionType = {
  GET_ALL_CUSTOMERS: 'GET_ALL_CUSTOMERS',
  GET_CUSTOMER_PROFILE: 'GET_CUSTOMER_PROFILE',
  SET_INITIAL_STATE: 'SET_INITIAL_STATE',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
}
