export const actionType = {
  GET_ALL_MATTER_CANCELLATIONS: 'GET_ALL_MATTER_CANCELLATIONS',
  GET_MATTER_CANCELLATION: 'GET_MATTER_CANCELLATION',
  SET_INITIAL_STATE: 'SET_INITIAL_STATE',
  LOADING: 'LOADING',
  ERROR: 'ERROR'
}
