export const actionType = {
  GET_ALL_USERS: 'GET_ALL_USERS',
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_USER_FROM_ACADEMIC_PROCESS: 'GET_USER_FROM_ACADEMIC_PROCESS',
  SET_INITIAL_STATE: 'SET_INITIAL_STATE',
  LOADING: 'LOADING',
  ERROR: 'ERROR',
}
